import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { stringify, parse } from "smol-toml";
import { paths } from "./paths.js";

export interface HuskConfig {
	server?: {
		port?: number;
		db_path?: string;
		jwt_secret?: string;
	};
	storage?: {
		backend?: string;
		url?: string;
		path?: string;
		custom_sqlite?: string;
	};
	embeddings?: {
		backend?: string;
		url?: string;
		model?: string;
		api_key?: string;
		dimensions?: number;
		models_path?: string;
	};
	compression?: {
		provider?: string;
		api_key?: string;
		model?: string;
		url?: string;
		mode?: string;
	};
	graph?: {
		backend?: string;
		url?: string;
		user?: string;
		password?: string;
	};
	auth?: {
		github_client_id?: string;
		github_client_secret?: string;
		oauth_allowed_orgs?: string;
	};
}

export function defaultConfig(): HuskConfig {
	return {
		server: {
			port: 3000,
			db_path: paths.dbPath,
		},
		storage: {
			backend: "sqlite-vec",
			path: paths.vectorsPath,
		},
		embeddings: {
			backend: "transformers",
			models_path: paths.modelsPath,
		},
	};
}

export function writeConfig(config: HuskConfig, configPath?: string): void {
	const target = configPath ?? paths.config;
	mkdirSync(dirname(target), { recursive: true });

	// Filter out undefined values
	const clean = JSON.parse(JSON.stringify(config));
	const toml = stringify(clean);

	writeFileSync(target, `# HUSK Configuration\n# Generated by husk CLI\n\n${toml}\n`);
}

export function readConfig(configPath?: string): HuskConfig | null {
	const target = configPath ?? paths.config;
	if (!existsSync(target)) return null;

	try {
		const raw = readFileSync(target, "utf-8");
		return parse(raw) as HuskConfig;
	} catch {
		return null;
	}
}

export function resolveConfigPath(): string {
	// Check CWD first, then default location
	const cwdConfig = "husk.toml";
	if (existsSync(cwdConfig)) return resolve(cwdConfig);
	return paths.config;
}

export function mergeConfig(
	base: HuskConfig,
	overrides: HuskConfig,
): HuskConfig {
	const result: HuskConfig = { ...base };

	for (const section of [
		"server",
		"storage",
		"embeddings",
		"compression",
		"graph",
		"auth",
	] as const) {
		if (overrides[section]) {
			result[section] = { ...base[section], ...overrides[section] };
		}
	}

	return result;
}
