import { writeFileSync } from "node:fs";
import { join } from "node:path";

interface DockerServices {
	qdrant?: boolean;
	ollama?: { model?: string };
}

export function generateDockerCompose(
	services: DockerServices,
	outputDir: string,
): string {
	const lines: string[] = [
		"# Generated by husk CLI",
		"services:",
	];

	const volumes: string[] = [];

	if (services.qdrant) {
		lines.push(
			"  qdrant:",
			"    image: qdrant/qdrant:latest",
			"    volumes:",
			"      - qdrant_data:/qdrant/storage",
			"    ports:",
			'      - "6333:6333"',
			"    restart: unless-stopped",
			"",
		);
		volumes.push("  qdrant_data:");
	}

	if (services.ollama) {
		const raw = services.ollama.model ?? "nomic-embed-text";
		// Sanitize: ollama model names are alphanumeric with colons, dashes, dots, underscores, slashes
		const model = raw.replace(/[^a-zA-Z0-9:._\-/]/g, "");
		lines.push(
			"  ollama:",
			"    image: ollama/ollama:latest",
			"    volumes:",
			"      - ollama_data:/root/.ollama",
			"    ports:",
			'      - "11434:11434"',
			"    restart: unless-stopped",
			"    healthcheck:",
			'      test: ["CMD", "ollama", "list"]',
			"      interval: 5s",
			"      timeout: 3s",
			"      start_period: 5s",
			"",
			"  ollama-pull:",
			"    image: curlimages/curl:latest",
			"    depends_on:",
			"      ollama:",
			"        condition: service_healthy",
			'    restart: "no"',
			`    entrypoint: ["sh", "-c", "curl -fSL http://ollama:11434/api/pull -d '{\\"name\\":\\"${model}\\",\\"stream\\":false}'"]`,
			"",
		);
		volumes.push("  ollama_data:");
	}

	if (volumes.length > 0) {
		lines.push("volumes:", ...volumes);
	}

	const content = lines.join("\n") + "\n";
	const outputPath = join(outputDir, "docker-compose.yml");
	writeFileSync(outputPath, content);

	return outputPath;
}
